### ISSUE TITLE
unable to connect to plex server over http

### ISSUE THREAD

**Issue by PsEHAmfxXNKzrgwT** [jcostom/rollerblades#36]
Hi,

unable to connect to my plex server, tried via http and hostname with https,

logs:

`ErrorWarningSystemArrayLogin

[INFO] [27 Oct 2024 13:31:17 GMT] Startup rollerblades.py/1.1.8.
[INFO] [27 Oct 2024 13:31:17 GMT] Loaded in prerolls data from /config/prerolls.json.
[DEBUG] [27 Oct 2024 13:31:17 GMT] Starting new HTTP connection (1): 10.100.100.4:32400
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 199, in _new_conn
sock = connection.create_connection(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
raise err
File "/usr/local/lib/python3.12/site-packages/urllib3/util/connection.py", line 73, in create_connection
sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
response = self._make_request(
^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 495, in _make_request
conn.request(
File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 441, in request
self.endheaders()
File "/usr/local/lib/python3.12/http/client.py", line 1331, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/usr/local/lib/python3.12/http/client.py", line 1091, in _send_output
self.send(msg)
File "/usr/local/lib/python3.12/http/client.py", line 1035, in send
self.connect()
File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 279, in connect
self.sock = self._new_conn()
^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 208, in _new_conn
raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x14c0e6d4a7b0>, 'Connection to 10.100.100.4 timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
resp = conn.urlopen(
^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
retries = retries.increment(
^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
raise MaxRetryError(_pool, url, reason) from reason # type: ignore[arg-type]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.100.100.4', port=32400): Max retries exceeded with url: /:/prefs?X-Plex-Token=zJxxpau2a41ejQbNQyyy (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x14c0e6d4a7b0>, 'Connection to 10.100.100.4 timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/app/rollerblades.py", line 109, in <module>
main()
File "/app/rollerblades.py", line 80, in main
current_preroll = get_current_preroll(SCHEME, HOST, PORT, TOKEN)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/rollerblades.py", line 49, in get_current_preroll
r = requests.get(url, headers=HEADERS, verify=False)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 73, in get
return request("get", url, params=params, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 59, in request
return session.request(method=method, url=url, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
resp = self.send(prep, **send_kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
r = adapter.send(request, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 688, in send
raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='10.100.100.4', port=32400): Max retries exceeded with url: /:/prefs?X-Plex-Token=zJxxpau2a41ejQbNQyyy (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x14c0e6d4a7b0>, 'Connection to 10.100.100.4 timed out. (connect timeout=None)'))`

**Comment by PsEHAmfxXNKzrgwT** [comment]
tried new token and ip address is 100% accurate

**Comment by jcostom** [comment]
I looked into this, and I can't replicate your issue. Is your Plex server running on port 32400?

**Comment by jcostom** [comment]
Closing this as reporter has been unresponsive.
